### ISSUE TITLE
Booking Service TODO

### ISSUE THREAD

**Issue by mslaursen** [3rd-semester-sd/bachelor-project#3]
* [ ] Setup project with an initial endpoint 

Setup local development environment, without dependencies 
* * [ ] Dockerfile
* * [ ] Kubernetes + tilt
* * [ ] Dockercompose (optional)

* [ ] Deploy the service with Terraform (azure)
* [ ] setup database connection, ensuring it works with the kube cluster
* [ ] add a health endpoint and add the kubernetes files for postgres
